[package]
name = "send-directory"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.5.4", features = ["derive"] }
futures-util = "^0.3.30"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = "*"

futures-channel = "^0.3.28"
zip = "^0.6"